- name: Automate Terraform Tasks on Azure VM
  hosts: azure-vm
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: ['git', 'wget', 'unzip', 'curl']
        state: present
        update_cache: true

    - name: Download and install Terraform
      shell: |
        curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        mv terraform /usr/local/bin/
        terraform -version
      args:
        chdir: /tmp

    - name: Clone GitHub repo with Terraform code
      git:
        repo: https://github.com/Akash-coder8147/your-tf-repo.git
        dest: /home/azureuser/tf-repo

    - name: Execute Terraform
      shell: |
        terraform init
        terraform apply -auto-approve
      args:
        chdir: /home/azureuser/tf-repo
      register: tf_output

    - name: Show Terraform Output
      debug:
        var: tf_output.stdout_lines

    - name: Cleanup Cloned Repo
      file:
        path: /home/azureuser/tf-repo
        state: absent

